-- ==========================
-- JOINS
-- ==========================

-- 1. Display every order with customer name, book title and author

SELECT
    o.order_id,
    c.name AS customer_name,
    b.title,
    b.author,
    o.quantity,
    o.total_amount
FROM Orders o
JOIN Customers c
ON o.customer_id=c.customer_id
JOIN Books b
ON o.book_id=b.book_id
ORDER BY o.order_id;



-- 2. Find the top 5 highest revenue generating books

SELECT
    b.book_id,
    b.title,
    SUM(o.total_amount) AS revenue
FROM Books b
JOIN Orders o
ON b.book_id=o.book_id
GROUP BY
    b.book_id,
    b.title
ORDER BY revenue DESC
LIMIT 5;



-- 3. Find customers who purchased books from more than one genre

SELECT
    c.customer_id,
    c.name,
    COUNT(DISTINCT b.genre) AS genres_purchased
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
JOIN Books b
ON o.book_id=b.book_id
GROUP BY
    c.customer_id,
    c.name
HAVING COUNT(DISTINCT b.genre)>1;



-- ==========================
-- AGGREGATE ANALYSIS
-- ==========================

-- 4. Calculate average order value for every customer

SELECT
    c.customer_id,
    c.name,
    ROUND(AVG(o.total_amount),2) AS avg_order_value
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY avg_order_value DESC;



-- 5. Find authors who sold more than 10 books

SELECT
    b.author,
    SUM(o.quantity) AS books_sold
FROM Books b
JOIN Orders o
ON b.book_id=o.book_id
GROUP BY b.author
HAVING SUM(o.quantity)>10
ORDER BY books_sold DESC;



-- 6. Calculate total revenue generated by every genre

SELECT
    b.genre,
    SUM(o.total_amount) AS revenue
FROM Books b
JOIN Orders o
ON b.book_id=o.book_id
GROUP BY b.genre
ORDER BY revenue DESC;



-- ==========================
-- CASE
-- ==========================

-- 7. Classify customers based on total spending

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent,
    CASE
        WHEN SUM(o.total_amount)>=1000 THEN 'Premium'
        WHEN SUM(o.total_amount)>=500 THEN 'Regular'
        ELSE 'Occasional'
    END AS customer_type
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY total_spent DESC;



-- ==========================
-- SUBQUERIES
-- ==========================

-- 8. Find books priced above the overall average

SELECT
    book_id,
    title,
    price
FROM Books
WHERE price>
(
    SELECT AVG(price)
    FROM Books
)
ORDER BY price DESC;



-- 9. Find customers whose total spending is above the average customer spending

SELECT
    customer_id,
    name,
    total_spent
FROM
(
    SELECT
        c.customer_id,
        c.name,
        SUM(o.total_amount) AS total_spent
    FROM Customers c
    JOIN Orders o
    ON c.customer_id=o.customer_id
    GROUP BY
        c.customer_id,
        c.name
) spending
WHERE total_spent>
(
    SELECT AVG(total_spent)
    FROM
    (
        SELECT
            SUM(total_amount) AS total_spent
        FROM Orders
        GROUP BY customer_id
    ) avg_spending
);



-- ==========================
-- BUSINESS INSIGHTS
-- ==========================

-- 10. Calculate remaining stock after fulfilling all orders

SELECT
    b.book_id,
    b.title,
    b.stock,
    COALESCE(SUM(o.quantity),0) AS sold_quantity,
    b.stock-COALESCE(SUM(o.quantity),0) AS remaining_stock
FROM Books b
LEFT JOIN Orders o
ON b.book_id=o.book_id
GROUP BY
    b.book_id,
    b.title,
    b.stock
ORDER BY remaining_stock;



-- 11. Find the customer who generated the highest revenue

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY total_spent DESC
LIMIT 1;



-- 12. Find books that have never been ordered

SELECT
    b.book_id,
    b.title
FROM Books b
LEFT JOIN Orders o
ON b.book_id=o.book_id
WHERE o.order_id IS NULL;
-- ==========================
-- WINDOW FUNCTIONS
-- ==========================

-- 13. Rank customers based on total spending

SELECT
    c.customer_id,
    c.name,
    SUM(o.total_amount) AS total_spent,
    DENSE_RANK() OVER(
        ORDER BY SUM(o.total_amount) DESC
    ) AS spending_rank
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY spending_rank;


-- 14. Rank books within each genre by price

SELECT
    title,
    genre,
    price,
    DENSE_RANK() OVER(
        PARTITION BY genre
        ORDER BY price DESC
    ) AS genre_rank
FROM Books
ORDER BY genre,genre_rank;


-- 15. Assign row numbers to every order by amount

SELECT
    order_id,
    customer_id,
    total_amount,
    ROW_NUMBER() OVER(
        ORDER BY total_amount DESC
    ) AS row_num
FROM Orders;


-- 16. Compare ROW_NUMBER(), RANK() and DENSE_RANK()

SELECT
    order_id,
    total_amount,
    ROW_NUMBER() OVER(ORDER BY total_amount DESC) AS row_number,
    RANK() OVER(ORDER BY total_amount DESC) AS rank,
    DENSE_RANK() OVER(ORDER BY total_amount DESC) AS dense_rank
FROM Orders;


-- 17. Running revenue over time

SELECT
    order_date,
    total_amount,
    SUM(total_amount) OVER(
        ORDER BY order_date
    ) AS running_revenue
FROM Orders
ORDER BY order_date;


-- ==========================
-- CTEs
-- ==========================

-- 18. Find customers whose spending is above average

WITH customer_spending AS
(
    SELECT
        customer_id,
        SUM(total_amount) AS total_spent
    FROM Orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_spent
FROM customer_spending
WHERE total_spent>
(
    SELECT AVG(total_spent)
    FROM customer_spending
);


-- 19. Highest revenue generating genre

WITH genre_revenue AS
(
    SELECT
        b.genre,
        SUM(o.total_amount) AS revenue
    FROM Books b
    JOIN Orders o
    ON b.book_id=o.book_id
    GROUP BY b.genre
)

SELECT *
FROM genre_revenue
ORDER BY revenue DESC
LIMIT 1;


-- ==========================
-- ADVANCED BUSINESS ANALYSIS
-- ==========================

-- 20. Top selling book in each genre

SELECT *
FROM
(
    SELECT
        b.genre,
        b.title,
        SUM(o.quantity) AS books_sold,
        DENSE_RANK() OVER(
            PARTITION BY b.genre
            ORDER BY SUM(o.quantity) DESC
        ) AS rnk
    FROM Books b
    JOIN Orders o
    ON b.book_id=o.book_id
    GROUP BY
        b.genre,
        b.title
) ranked_books
WHERE rnk=1;


-- 21. Percentage contribution of every genre to total revenue

SELECT
    b.genre,
    ROUND(SUM(o.total_amount),2) AS revenue,
    ROUND(
        SUM(o.total_amount)*100.0/
        (SELECT SUM(total_amount) FROM Orders),
        2
    ) AS revenue_percentage
FROM Books b
JOIN Orders o
ON b.book_id=o.book_id
GROUP BY b.genre
ORDER BY revenue DESC;


-- 22. Monthly revenue trend

SELECT
    DATE_TRUNC('month',order_date) AS month,
    SUM(total_amount) AS revenue
FROM Orders
GROUP BY DATE_TRUNC('month',order_date)
ORDER BY month;


-- 23. Top 3 customers by spending

SELECT
    customer_id,
    name,
    total_spent
FROM
(
    SELECT
        c.customer_id,
        c.name,
        SUM(o.total_amount) AS total_spent,
        DENSE_RANK() OVER(
            ORDER BY SUM(o.total_amount) DESC
        ) AS rnk
    FROM Customers c
    JOIN Orders o
    ON c.customer_id=o.customer_id
    GROUP BY
        c.customer_id,
        c.name
) ranked_customers
WHERE rnk<=3;


-- 24. Customer Lifetime Value (CLV)

SELECT
    c.customer_id,
    c.name,
    COUNT(o.order_id) AS total_orders,
    SUM(o.total_amount) AS lifetime_value,
    ROUND(AVG(o.total_amount),2) AS average_order_value
FROM Customers c
JOIN Orders o
ON c.customer_id=o.customer_id
GROUP BY
    c.customer_id,
    c.name
ORDER BY lifetime_value DESC;
